import { ClassificationAssignment, KNOWLEDGE_NODES } from '@orc/shared';
import type { ReviewExportInput } from './types';

export function buildKnowledgeTree(assignments: ClassificationAssignment[]) {
  return {
    hierarchy: 'flat-default-wave01',
    nodes: KNOWLEDGE_NODES.map((node, index) => {
      const assigned = assignments.filter((a) => a.nodeId === node.id);
      return {
        nodeId: node.id,
        nodeName: node.label,
        hierarchy: {
          level: 1,
          order: index + 1,
          parentId: null,
        },
        color: node.color,
        assignedTextCount: assigned.length,
        assignedTexts: assigned.map((a) => ({
          id: a.id,
          pageNumber: a.pageNumber,
          text: a.text,
        })),
      };
    }),
  };
}

export function buildHighlights(assignments: ClassificationAssignment[]) {
  return {
    items: assignments.map((a) => {
      const node = KNOWLEDGE_NODES.find((n) => n.id === a.nodeId);
      return {
        id: a.id,
        page: a.pageNumber,
        color: node?.color ?? '#7F7F7F',
        nodeId: a.nodeId,
        nodeName: node?.label ?? a.nodeId,
        start: 0,
        end: a.text.length,
        text: a.text,
      };
    }),
  };
}

export function buildEvidence(
  evidence: ReviewExportInput['evidence'],
) {
  return {
    items: evidence.map((e) => ({
      evidenceId: e.id ?? `${e.documentId}-${e.nodeId}-${e.timestamp}`,
      timestamp: e.timestamp,
      operation: e.type,
      reviewer: e.reviewer,
      version: e.version,
      nodeId: e.nodeId,
      before: e.before,
      after: e.after,
      documentId: e.documentId,
    })),
  };
}

export function buildSession(input: ReviewExportInput) {
  const endedAt = new Date().toISOString();
  const durationMs = Math.max(
    0,
    Date.parse(endedAt) - Date.parse(input.sessionStartedAt),
  );
  const count = (type: string) =>
    input.sessionEvents.filter((e) => e.type === type).length;

  return {
    documentId: input.document.id,
    startedAt: input.sessionStartedAt,
    endedAt,
    durationMs,
    counts: {
      import: count('import'),
      highlight: count('highlight'),
      assign: count('assign'),
      undo: count('undo'),
      redo: count('redo'),
      save: count('save'),
    },
    events: input.sessionEvents,
    snapshot: input.snapshot,
  };
}

export function buildPerformance(input: ReviewExportInput) {
  type PerfMemory = {
    usedJSHeapSize: number;
    totalJSHeapSize: number;
    jsHeapSizeLimit: number;
  };
  const perfWithMemory = performance as Performance & { memory?: PerfMemory };
  const memory = perfWithMemory.memory
    ? {
        usedJSHeapSize: perfWithMemory.memory.usedJSHeapSize,
        totalJSHeapSize: perfWithMemory.memory.totalJSHeapSize,
        jsHeapSizeLimit: perfWithMemory.memory.jsHeapSizeLimit,
      }
    : null;

  return {
    renderTimeMs: input.renderTimeMs,
    memory,
    documentSizeBytes: input.document.sizeBytes,
    highlightCount: input.assignments.length,
    evidenceCount: input.evidence.length,
  };
}

export function buildEnvironment() {
  return {
    stoneVersion: 'STONE-01',
    buildVersion: process.env.NEXT_PUBLIC_BUILD_VERSION ?? '0.1.0-lab001',
    productName: 'HO Notice Assistant',
    browser: typeof navigator !== 'undefined' ? navigator.userAgent : 'unknown',
    resolution:
      typeof window !== 'undefined'
        ? {
            width: window.screen.width,
            height: window.screen.height,
            devicePixelRatio: window.devicePixelRatio,
            viewportWidth: window.innerWidth,
            viewportHeight: window.innerHeight,
          }
        : null,
    locale: typeof navigator !== 'undefined' ? navigator.language : 'vi',
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  };
}

export function buildReadme(): string {
  return [
    'Generated by',
    'ORC Stone-01',
    '',
    'Review Package',
    '',
    'Purpose',
    'Product Review',
    'Evidence',
    'UX Analysis',
    'Debug',
    '',
    'Contents',
    '- workspace.png',
    '- knowledge-tree.json',
    '- highlight.json',
    '- evidence.json',
    '- session.json',
    '- performance.json',
    '- environment.json',
    '- raw-text.json (DIL)',
    '- normalized-text.json (DIL)',
    '- confidence.json (DIL)',
    '- suspicious.json (DIL)',
    '- README.txt',
    '',
    'This is Evidence Export — not bug reporting, not telemetry.',
  ].join('\n');
}
